name: chesscoach
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - requests>=2.25.0
    - python-chess>=1.999
    - python-dotenv>=0.19.0
    - fastapi>=0.104.1
    - uvicorn[standard]>=0.24.0
    - pydantic>=2.5.0
    - python-multipart>=0.0.6
    - pytest>=7.0.0
    - httpx>=0.25.0
    - tqdm>=4.60.0
